# Generated by Django 5.2.1 on 2025-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
